In [2]:
from tensorflow.keras.models import load_model
from time import sleep
from keras.preprocessing.image import img_to_array
from keras.preprocessing import image
import cv2
import numpy as np

In [6]:
import os
os.chdir("/Users/simoneboesso/Desktop/Modelling_videos/RealTime_FaceEmotionRecognition")

In [10]:
model = load_model("final_model.h5")

In [13]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.txt')

class_labels=['Angry','Disgust', 'Fear', 'Happy','Neutral','Sad','Surprise']

cap=cv2.VideoCapture(0)
if not cap.isOpened():
    print("Main webcam is can't be opened")
    cap=cv2.VideoCapture(1)
    if not cap.isOpened():
        raise IOError("Cannot open secondary Webcam")
    

while True:
    ret,frame=cap.read() # each frame is one image
    print(frame)
    
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray,1.3,5)
    if len(faces) == 0:
        "Face is not detected"
        
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray=gray[y:y+h,x:x+w]
        roi_gray=cv2.resize(roi_gray,(224,224),interpolation=cv2.INTER_LANCZOS4)

        #Get image ready for prediction
        roi=roi_gray.astype('float')/255.0  #Scale
        roi=img_to_array(roi)
        roi=np.expand_dims(roi,axis=0)  #Expand dims to get it ready for prediction (1, 48, 48, 1)

        preds=model.predict(roi)[0]  #Yields one hot encoded result for 7 classes
        label=class_labels[preds.argmax()]  #Find the label
        label_position=(x,y)
        cv2.putText(frame,label,label_position,cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
        
   
    cv2.imshow('Emotion Detector', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

[[[206 234 195]
  [205 233 194]
  [208 235 196]
  ...
  [ 96 101 119]
  [105 111 128]
  [118 124 141]]

 [[209 236 197]
  [206 234 195]
  [210 237 198]
  ...
  [ 90  96 113]
  [102 107 125]
  [109 114 132]]

 [[210 237 198]
  [206 234 195]
  [211 238 199]
  ...
  [ 90  93 111]
  [ 99 102 120]
  [110 113 130]]

 ...

 [[202 199 143]
  [203 200 144]
  [203 200 146]
  ...
  [ 25  15  29]
  [ 32  22  36]
  [ 37  28  42]]

 [[201 198 141]
  [201 198 141]
  [202 199 144]
  ...
  [ 35  25  40]
  [ 32  22  36]
  [ 28  18  33]]

 [[201 198 141]
  [201 198 141]
  [202 199 144]
  ...
  [ 32  22  36]
  [ 29  20  34]
  [ 34  24  38]]]


ValueError: in user code:

    File "/Users/simoneboesso/anaconda3/envs/transformer/lib/python3.10/site-packages/keras/src/engine/training.py", line 2341, in predict_function  *
        return step_function(self, iterator)
    File "/Users/simoneboesso/anaconda3/envs/transformer/lib/python3.10/site-packages/keras/src/engine/training.py", line 2327, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/simoneboesso/anaconda3/envs/transformer/lib/python3.10/site-packages/keras/src/engine/training.py", line 2315, in run_step  **
        outputs = model.predict_step(data)
    File "/Users/simoneboesso/anaconda3/envs/transformer/lib/python3.10/site-packages/keras/src/engine/training.py", line 2283, in predict_step
        return self(x, training=False)
    File "/Users/simoneboesso/anaconda3/envs/transformer/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/Users/simoneboesso/anaconda3/envs/transformer/lib/python3.10/site-packages/keras/src/engine/input_spec.py", line 280, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer 'model' (type Functional).
    
    Input 0 of layer "Conv1" is incompatible with the layer: expected axis -1 of input shape to have value 3, but received input with shape (None, 224, 224, 1)
    
    Call arguments received by layer 'model' (type Functional):
      • inputs=tf.Tensor(shape=(None, 224, 224, 1), dtype=float32)
      • training=False
      • mask=None
